### ISSUE TITLE
项目冷启动时间50S，有考虑优化么？

### ISSUE THREAD

**Issue by HOLYYUN** [buqiyuan/vue3-antdv-admin#102]
项目冷启动时间50S，有考虑优化么？

**Comment by buqiyuan** [comment]
冷启动这个优化提升不明显，因为webpack是先打包，然后才启动开发服务器。你可以考虑使用swc替代babel，或者开发时按条件加载loader，减少开发时不必要的transform。项目中用到了webpack5的持久化缓存，二次构建速度应该很快，后面再优化一下吧！应该还能提升个几秒
