### ISSUE TITLE
defineOptions is not defined

### ISSUE THREAD

**Issue by HOLYYUN** [buqiyuan/vue3-antdv-admin#103]
使用unplugin-vue-define-options在production环境中会产生下面这个问题，我去插件github看了 目前还没有根本解决这个bug
![image](https://user-images.githubusercontent.com/22185629/175272184-eb9abc91-fe85-41d3-97c6-1070b27db61d.png)

**Comment by buqiyuan** [comment]
我在当前这个项目里面没有遇到这个问题，`unplugin-vue-define-options`相关[issues](https://github.com/sxzz/unplugin-vue-define-options/issues/23#issuecomment-1170283222)貌似有临时解决方法了

**Comment by zjluse** [comment]
发现把node_modules删掉，重新install，马上再build就不会有问题， 但是偶尔关机或者重启编辑器可能就会再次报错！
