### ISSUE TITLE
【建议】hook useI18n再封装

### ISSUE THREAD

**Issue by kerwin-ly** [buqiyuan/vue3-antdv-admin#105]
>主要用于配合vscode i18nn ally插件的提示。此功能仅用于路由和菜单。请在其他地方使用 vue-i18n 的 useI18n

项目中针对国际化的hook，既使用了`vue-i18n`，又使用了hooks自定义封装的`i18n`。在使用的时候容易混淆。可以对`useI18n()`再次封装，让使用者仅引用自定义的`useI18n()`么？把判断逻辑放在hook内部，而不是让用户来区分应该引用哪个`useI18n()`

当前代码示例：
```ts
import { useI18n } from 'vue-i18n';
...
import { useI18n } from '@/hooks/useI18n';
```

**Comment by buqiyuan** [comment]
👍谢谢建议！确实应该统一引用一处，降低心智负担
