### ISSUE TITLE
你封装基础组件时候的思路是怎么样的呢？

### ISSUE THREAD

**Issue by qtencent7** [buqiyuan/vue3-antdv-admin#115]
补充一下：是先写页面，还是先封装的呢？

**Comment by buqiyuan** [comment]
如果不是经验丰富的巨佬的话，建议先从页面、业务开始做，业务做多了，你就会慢慢的发现很多代码/逻辑都是类似的，这时候你就会考虑封装，把它们的通用能力抽取出来，慢慢的就形成项目的基础组件和业务组件了。等你积累足够多的业务经验和痛点后，自然而然地你就知道一个新项目需要做好哪些基础建设了
