### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by tiantianliulang** [buqiyuan/vue3-antdv-admin#117]
如图，设置每页显示数量后，再切换其他页数，没生效！

![image](https://user-images.githubusercontent.com/77230009/190845461-ca988a6b-a5a4-494e-b5e3-db1ab91f3e56.png)
![image](https://user-images.githubusercontent.com/77230009/190845580-d230a7fa-366e-434f-a5c2-40675f74ec34.png)

**Comment by buqiyuan** [comment]
https://github.com/buqiyuan/vue3-antdv-admin/blob/bff5aeb86fe15547b6abb4d00e53b9f6dbcb8f1a/src/components/core/dynamic-table/src/dynamic-table.config.ts#L16-L21
