### ISSUE TITLE
tabs无法滚动

### ISSUE THREAD

**Issue by zengxiangliang** [buqiyuan/vue3-antdv-admin#121]
顶部tabs无法手动控制滚动

**Comment by buqiyuan** [comment]
溢出的 tabs 暂时只支持通过右侧下拉切换 tab
<img width="962" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/9e50a70f-aaf1-4ade-9c52-dcc00cb1df00">
