### ISSUE TITLE
Cannot access 'SchemaForm' before initialization

### ISSUE THREAD

**Issue by bighamD** [buqiyuan/vue3-antdv-admin#129]
##  控制台错误
Uncaught (in promise) ReferenceError: Cannot access 'SchemaForm' before initialization
/#/frame/upload/TRAIN_VIDEO对于这种多级路由，页面内容存在Schema, 如果页面刷新就会报错

#### Steps to reproduce（问题复现步骤）
![image](https://github.com/buqiyuan/vue3-antd-admin/assets/41603686/55fea497-77eb-4538-80f8-86f724f23592)

**Comment by FQIP** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by bighamD** [comment]
我把你这里代码注释掉，相关引用也改掉就ok了
![image](https://github.com/buqiyuan/vue3-antd-admin/assets/41603686/7cd30ab2-c55f-4f45-8779-1166e9be7279)

![image](https://github.com/buqiyuan/vue3-antd-admin/assets/41603686/b002fdeb-3079-48cc-b20e-e312c2940b0d)
