### ISSUE TITLE
我想要实现数字区间的查询，但是琢磨了半天，加不上去。

### ISSUE THREAD

**Issue by BericBig** [buqiyuan/vue3-antdv-admin#131]
![image](https://github.com/buqiyuan/vue3-antd-admin/assets/70929203/b6ca2787-034b-420c-a105-1547d83933f4)
请问有什么比较好的办法解决这个问题么？

**Comment by buqiyuan** [comment]
通过 `component: () => inputNumberRange`使用自定义组件：
https://github.com/buqiyuan/vue3-antdv-admin/blob/9590d226f4b129bbaa0a4a84bec01760c40a7a1a/src/views/demos/form/custom-form/index.vue#L22-L41

`inputNumberRange` 组件内容：
https://github.com/buqiyuan/vue3-antdv-admin/blob/9590d226f4b129bbaa0a4a84bec01760c40a7a1a/src/views/demos/form/custom-form/input-number-range.vue#L1-L41
