### ISSUE TITLE
页面锁屏功能探讨🙏

### ISSUE THREAD

**Issue by easymoneysniperrr** [buqiyuan/vue3-antdv-admin#139]
## Feature request（新功能建议）
大佬的锁屏在后台管理系统很新意，我正在尝试实现。但是我在看大佬代码实现的时候发现控制锁屏的IS_LOCKSCREEN是存放在localstorage里的。用户是可以通过控制台手动修改storage里的值的，然后再刷新页面就可以解除锁屏的状态。
请问是我操作理解有问题，还是说确实有这个缺陷。

**Comment by buqiyuan** [comment]
这个锁屏功能本身也是做着玩的，如果仅靠纯前端做锁屏，肯定是不够严谨的，稍微懂点浏览器调试技巧的都可以轻松破解，防君子不防小人的
