### ISSUE TITLE
您NodeJs是用哪个版本的？我npm install还跑不起来

### ISSUE THREAD

**Issue by sunfeng90** [buqiyuan/vue3-antdv-admin#144]
我尝试了node18和node20，安装npm install，一直报错，您用的哪个版本？

**Comment by buqiyuan** [comment]
建议用 `pnpm` 安装

**Comment by jdami** [comment]
v18.19.0 亲测可用。 建议用pnpm装 其他的装好像都不太好使。

**Comment by sunfeng90** [comment]
安装成功了，目前部署到服务器，发现登录不了。

env.production的VITE_BASE_URL是什么意思，我写/就登录后就加载不了
