### ISSUE TITLE
注释 demos 路由后会报错

### ISSUE THREAD

**Issue by imruxin** [buqiyuan/vue3-antdv-admin#148]
对这个文件 src/router/routes/modules/index.ts 中的demos 路由注释后，运行会报错。
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/5736012/8274e9c5-d9ae-475e-90a4-4432e70ff779)

结果报：
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/5736012/783c6334-5c79-455d-80dc-178f04fbc00e)

目前不清楚是什么原因

**Comment by buqiyuan** [comment]
暂时不清楚具体原因，尝试将 `typescript` 的版本降到 `5.2.2`看看

**Comment by imruxin** [comment]
> 暂时不清楚具体原因，尝试将 `typescript` 的版本降到 `5.2.2`看看

版本降级后验证是正常了
