### ISSUE TITLE
feature: 新功能，请问有计划对 H5 适配计划吗？

### ISSUE THREAD

**Issue by WuChenDi** [buqiyuan/vue3-antdv-admin#150]
## Feature request（新功能建议）

> 移动端适配优化

### 场景描述：

在当前使用的后台模板中，不同部门具有各自独特的访问权限需求。考虑到部分部门的工作人员需要在移动设备上进行操作，我们提出了对现有系统进行移动端适配优化的需求。此次优化旨在不对现有系统架构进行大规模改动的前提下，实现对移动设备友好的操作界面，以满足跨设备使用的便捷性。

**Comment by buqiyuan** [comment]
暂时没有适配移动端的计划，但是项目中使用 `<meta name="viewport" content="user-scalable=yes" />` 可以确保网页在移动设备上具有良好的可缩放性，并提供更灵活的用户体验。

**Comment by WuChenDi** [comment]
Thanks for the reply, issues closed
