### ISSUE TITLE
Node 18.17, pnpm dev ,运行出错error when starting dev server: Error: read ECONNRESET at AxiosError.from

### ISSUE THREAD

**Issue by guozanhua** [buqiyuan/vue3-antdv-admin#152]
#### Other relevant information（格外信息）

- Your OS:
- Node.js version:
- packageManager:

**Comment by guozanhua** [comment]
> vue3-antdv-admin@2.0.0 dev D:\work\shottinggames\vue3-antdv-admin-main
> vite
index.cjs:32The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
dep-jDlpJiMN.js:13167error when starting dev server: Error: read ECONNRESET at AxiosError.from (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\axios@1.6.7_debug@4.3.4\node_modules\axios\dist\node\axios.cjs:837:14) at RedirectableRequest.handleRequestError (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\axios@1.6.7_debug@4.3.4\node_modules\axios\dist\node\axios.cjs:3087:25) at RedirectableRequest.emit (node:events:517:28) at eventHandlers.<computed> (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\follow-redirects@1.15.5_debug@4.3.4\node_modules\follow-redirects\index.js:38:24) at ClientRequest.emit (node:events:517:28) at TLSSocket.socketErrorListener (node:_http_client:501:9) at TLSSocket.emit (node:events:517:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) at Axios.request (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\axios@1.6.7_debug@4.3.4\node_modules\axios\dist\node\axios.cjs:3877:41) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _Downloader.download (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\vite-plugin-mkcert@1.17.3_vite@5.1.4\node_modules\vite-plugin-mkcert\dist\mkcert.js:234:22) at async _Mkcert.downloadMkcert (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\vite-plugin-mkcert@1.17.3_vite@5.1.4\node_modules\vite-plugin-mkcert\dist\mkcert.js:614:5) at async _Mkcert.initMkcert (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\vite-plugin-mkcert@1.17.3_vite@5.1.4\node_modules\vite-plugin-mkcert\dist\mkcert.js:580:5) at async _Mkcert.init (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\vite-plugin-mkcert@1.17.3_vite@5.1.4\node_modules\vite-plugin-mkcert\dist\mkcert.js:564:7) at async config (D:\work\shottinggames\vue3-antdv-admin-main\node_modules\.pnpm\vite-plugin-mkcert@1.17.3_vite@5.1.4\node_modules\vite-plugin-mkcert\dist\mkcert.js:673:7) at async runConfigHook (file:///D:/work/shottinggames/vue3-antdv-admin-main/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.16_less@4.2.0_lightningcss@1.23.0_terser@5.27.2/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:68189:25) at async resolveConfig (file:///D:/work/shottinggames/vue3-antdv-admin-main/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.16_less@4.2.0_lightningcss@1.23.0_terser@5.27.2/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67648:14) at async _createServer (file:///D:/work/shottinggames/vue3-antdv-admin-main/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.16_less@4.2.0_lightningcss@1.23.0_terser@5.27.2/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:64257:20) at async CAC.<anonymous> (file:///D:/work/shottinggames/vue3-antdv-admin-main/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.16_less@4.2.0_lightningcss@1.23.0_terser@5.27.2/node_modules/vite/dist/node/cli.js:762:24)

OS:Win11
Nodejs:18.17
PNPM:8.15.3

**Comment by buqiyuan** [comment]
看起来像是网络错误，应该是 `vite-plugin-mkcert`插件尝试通过网络下载 `https` 正书到本地时，发送网络请求失败了，你可以在 `vite.config.ts` 里面找到 `vite-plugin-mkcert`插件相关代码并将其注释掉再试试
