### ISSUE TITLE
部署到服务器，直接报错了，不知道是否可以指导一下？

### ISSUE THREAD

**Issue by sunfeng90** [buqiyuan/vue3-antdv-admin#153]
我把前端打成dist的包，然后部署到服务器上。

我将env.production的VITE_BASE_URL修改为 /

我nginx的配置如下：

    server {
       listen 8084;
       server_name XXX.net www.XXX.net;
       root  /root/project/frontend/PC/badmintion/client/;
       index index.html index.htm index.php;
    }

   我把dist下面的所有文件直接放到/root/project/frontend/PC/badmintion/client/下面，不知道如何解决。本地正常的。

**Comment by buqiyuan** [comment]
`VITE_BASE_URL ` 是设置资源的公共路径的，如果你部署在根目录的话，用`/`没错。请问可以把相关报错信息截图看一下吗？因为我本地构建后的dist preview 是没问题的

**Comment by sunfeng90** [comment]
我本地是好的，我部署到腾讯云就不行了，下面是点击登录报错

**Comment by sunfeng90** [comment]
![6b43c5e90aaa3d020157d46a0f8f49f7](https://github.com/buqiyuan/vue3-antdv-admin/assets/11543206/2284a87d-8980-43de-82c9-6e80c20a3415)
上面是点击登录报错

**Comment by sunfeng90** [comment]
nginx对应的配置：

server {
       listen 8084;
       server_name  XXX.net www.XXX.net;
       root  /root/project/frontend/PC/XXX/client/;
       index index.html index.htm index.php;
    }

我访问的地址是：http://ip:8084/

结果点击登录就报错

**Comment by buqiyuan** [comment]
看样子前端应用是成功部署了，但貌似是因为 axios 接口请求路径不正确导致报错了，http://ip:8084/ 是你部署的在线地址吗？访问不了，你可以自行检查一下接口请求地址是否正确

**Comment by buqiyuan** [comment]
噢~你用的是旧版的代码，可能是 mockjs 的问题，你把 mock 相关的代码注释掉，看看是不是由于 mockjs 影响的

**Comment by sunfeng90** [comment]
是请求后端接口地址少了一个/

你后端部署用什么的？我用pm2，发现登录请求提示网络错误（Network Error）。

**Comment by sunfeng90** [comment]
最后用nohup 在后台运行npm start解决问题

**Comment by sunfeng90** [comment]
权限不同，配置不同的菜单，这一块好像有问题吧？我这里报错，超管倒是可以

**Comment by buqiyuan** [comment]
> 权限不同，配置不同的菜单，这一块好像有问题吧？我这里报错，超管倒是可以

复现了，之前不小心误改了 `definePermission` 方法，现已在 [nest-admin](https://github.com/buqiyuan/nest-admin/commit/3ec4757e76e0314671b482e8f59d5936fa44842e) 侧修复。

**Comment by sunfeng90** [comment]
好的，谢谢。你们这套代码是免费开源的吧？

**Comment by sunfeng90** [comment]
可以免费商用吧？

**Comment by buqiyuan** [comment]
完全免费，不限制任何用途，放心使用。

**Comment by sunfeng90** [comment]
牛逼的大佬！送上免费的star支持一下。
