### ISSUE TITLE
请问当前是否支持 eslint autofix onsave？

### ISSUE THREAD

**Issue by AAAAsea** [buqiyuan/vue3-antdv-admin#156]
vscode 已经安装了 eslint 插件，编辑器内也可以看到 eslint 的报红，但无法在保存时自动修复，我看`.vscode/setting.json` 已经有如下配置了，但不生效，只能手动`pnpm lint`进行修复吗？
```json
  "editor.codeActionsOnSave": {
    "source.fixAll": "explicit",
    "source.fixAll.stylelint": "explicit",
    "source.fixAll.eslint": "explicit"
  }
```

**Comment by buqiyuan** [comment]
🤔 保存时自动修复是通过 `esbenp.prettier-vscode` 插件进行修复的，你安装 `prettier` 的 vscode 插件了吗？

**Comment by AAAAsea** [comment]
> 🤔 保存时自动修复是通过 `esbenp.prettier-vscode` 插件进行修复的，你安装 `prettier` 的 vscode 插件了吗？

可以了，感谢作者大大！插件被我禁用了，我之前一直纠结于 Eslint 插件...
