### ISSUE TITLE
弹窗内容太长了，看不到提交和取消按钮。只能拖动弹窗页面才能显示出现

### ISSUE THREAD

**Issue by Fluox-Etine** [buqiyuan/vue3-antdv-admin#158]
<img width="855" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/64512602/2049a839-a444-4072-bc12-2e30c5b99b91">

<img width="909" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/64512602/04b5fe39-703b-4a57-8d1d-9ce10b1ac663">

期望就是能下滑页面看得到确认和取消按钮

**Comment by buqiyuan** [comment]
已修复 https://github.com/buqiyuan/vue3-antdv-admin/commit/b42729453ce5c7207f40fa8dc5a41e190e4b3819
