### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by dream-wk** [buqiyuan/vue3-antdv-admin#161]
## Bug report（问题描述）
Progress: resolved 1430, reused 1427, downloaded 0, added 2, done
node_modules/.pnpm/nx@18.1.2/node_modules/nx: Running postinstall script, failed in 551ms
.../.pnpm/nx@18.1.2/node_modules/nx postinstall$ node ./bin/post-install
│ E:\tem\vue3-antdv-admin-main\node_modules\.pnpm\nx@18.1.2\node_modules\nx\src\native\index.js:244
│     throw loadError
│     ^
│ Error: The specified module could not be found.
│ \\?\E:\tem\vue3-antdv-admin-main\node_modules\.pnpm\@nx+nx-win32-x64-msvc@18.1.2\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node
│     at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
#### Other relevant information（格外信息）

- Your OS:
- Node.js version:
- packageManager:

**Comment by buqiyuan** [comment]
没复现，要不你将 package.json 中的这行：
https://github.com/buqiyuan/vue3-antdv-admin/blob/271f63f5b762ca17cca2596845d6ac30705c99d1/package.json#L16
改为：
```diff
- "postinstall": "node ./scripts/postinstall.js || pnpm nx:build",
+ "postinstall": "pnpm build:pkg",
```

**Comment by dream-wk** [comment]
![图片](https://github.com/buqiyuan/vue3-antdv-admin/assets/49084585/fc5d26fb-9551-43d3-b4c6-b30d40ce8e71)
还是不行

**Comment by dream-wk** [comment]
有没有可能是我的版本问题呢  
node是18.19.1
pnpm 8.15.5

**Comment by buqiyuan** [comment]
版本看起来没问题，按理说你将 `postinstall` 脚本改为 `pnpm build:pkg` 之后，就没有执行 `nx` 相关的命令或脚本了呀🤔

**Comment by dream-wk** [comment]
![图片](https://github.com/buqiyuan/vue3-antdv-admin/assets/49084585/9a88d186-164e-4fca-a7d9-759fa0dbb703)
依赖删了 重新装 还是报错

**Comment by buqiyuan** [comment]
哦，原理 nx 自己还有个 postinstall 的脚本
<img width="884" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/4fa27da2-f9fb-4814-943d-c33f1a6e5cd1">
这样吧！你 `pnpm remove nx` 卸载掉 nx 这个包。
我 mac 复现不了你的问题，估计可能是电脑环境问题吧！

**Comment by buqiyuan** [comment]
刚在 [nx 官方文档](https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues#troubleshoot-nx-installations) 看了下，可能是这条没满足吧！没关系，你卸载掉 nx 也不影响什么，它只是用来提高 monorepo 构建效率的
<img width="1044" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/9d51f09e-4247-451d-8f38-76a21e3c2464">

**Comment by dream-wk** [comment]
![图片](https://github.com/buqiyuan/vue3-antdv-admin/assets/49084585/6a2d989b-6ae2-4214-9e41-a642d3c9155e)

**Comment by dream-wk** [comment]
我看了你两个插件都是有问题的

**Comment by dream-wk** [comment]
为啥呢
![Uploading 图片.png…]()

**Comment by buqiyuan** [comment]
插件本身没问题，你可以手动 pnpm build:pkg 构建好相关插件，然后再 pnpm install 应该就可以了。
因为我在 package.json 有如下的配置，pnpm 没有正常同步这两个依赖项，事实上这应该算是 pnpm 官方的 bug，详见此 [issue](https://github.com/pnpm/pnpm/issues/6088)
https://github.com/buqiyuan/vue3-antdv-admin/blob/271f63f5b762ca17cca2596845d6ac30705c99d1/package.json#L147-L153 
稍后，我将针对你这个情况做一个降级的处理，项目中 `scripts/postinstall.js` 这个脚本本身也是为了暂时兼容这个 bug 的
https://github.com/buqiyuan/vue3-antdv-admin/blob/main/scripts/postinstall.js#L1-L26

**Comment by dream-wk** [comment]
手动 pnpm build:pkg 构建好相关插件，然后再 pnpm install 应该就可以了

还是不行的   一样的报错

**Comment by buqiyuan** [comment]
🤔 如果方便远程的话，可以加我微信：bqy_fe

**Comment by rainywinter** [comment]
> 手动 pnpm build:pkg 构建好相关插件，然后再 pnpm install 应该就可以了
> 
> 还是不行的 一样的报错

我这里再执行一遍pnpm install 解决了`@admin-pkg/vite-plugin-` 的错误，能正常运行
