### ISSUE TITLE
表格控件点搜索或重置的时候下拉框的数据源会被清空

### ISSUE THREAD

**Issue by itwmike** [buqiyuan/vue3-antdv-admin#164]
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/6613191/2d0442ac-d19c-4aa4-9624-284c3bf7abf5)
![1711609256825](https://github.com/buqiyuan/vue3-antdv-admin/assets/6613191/0c3e1f95-92f6-4e25-a0cb-29c198267f8a)

**Comment by buqiyuan** [comment]
感谢反馈！改一下这两个地方就可以了，因为 `loadingRef` 变量的影响，导致 schemas 的状态丢失了
<img width="829" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/af387a16-c557-412e-91b0-e664c9de2363">
<img width="886" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/c74ce0b2-ab36-4f3e-a24b-79224a2494be">
