### ISSUE TITLE
大佬们如何优雅去掉 SSE 这个 websocket 接口阿？？？

### ISSUE THREAD

**Issue by Fluox-Etine** [buqiyuan/vue3-antdv-admin#165]
我这边项目暂时不需要这个接口，如何去掉阿？？？

**Comment by buqiyuan** [comment]
<img width="352" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/d2b93570-56f2-4179-bad5-7e451eb545d0">
引用到的地方不多，根据需要删减掉就好了
