### ISSUE TITLE
大佬怎么取消ts的验证啊

### ISSUE THREAD

**Issue by 732124645** [buqiyuan/vue3-antdv-admin#166]
大佬怎么取消ts的验证啊

**Comment by buqiyuan** [comment]
- 关闭编辑器 ts 校验：
`.vscode/settings.json` 中加入  `"typescript.validate.enable": true,`
- 注释以下代码，关闭运行时校验：
https://github.com/buqiyuan/vue3-antdv-admin/blob/efebda2b9e6d33d7b4e1808d3696feb1b1d039a7/vite.config.ts#L86-L97
