### ISSUE TITLE
菜单管理中新增按钮的权限问题

### ISSUE THREAD

**Issue by lixaviers** [buqiyuan/vue3-antdv-admin#167]
## Bug report（问题描述）
菜单管理-列表中新增按钮的权限控制有问题，只要不是权限类型就不禁用，权限控制有问题

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/22557284/ee80f332-d5a2-446b-9fc0-dd9a708eb63b)
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/22557284/f286ec30-a527-48d2-bce7-ec27afd63f70)

## 解决办法

`disabled: record.type === 2 || record.disable`

**Comment by buqiyuan** [comment]
有点道理，已改
<img width="644" alt="image" src="https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/86986d8f-0071-47cc-a153-dceecce92496">
