### ISSUE TITLE
componentProps中defaultValue设置后在表单提交中仍然报错值为空

### ISSUE THREAD

**Issue by eamd-wq** [buqiyuan/vue3-antdv-admin#168]
useFormModal中的showModal方法的formProps属性的schemas

其他内容如题 componentProps中defaultValue设置后在表单提交中仍然报错值为空，但直接写defaultValue是正常的

但此时在文本域InputTextAera组件中设置autoSize后 schemas数字中直接写的defaultValue虽可以展示但无法撑开文本域组件
目前的写法是componentProps.defaultValue和schemas[].defaultValue都写

![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/58057732/a5242e16-7cd7-4012-badf-8ea9799ae349)
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/58057732/4f2a13cd-49cf-496a-bcf2-de93af15b64c)

**Comment by buqiyuan** [comment]
**直接写defaultValue是正常的** ? 
你的 defaultValue 是一个原始值吗？方便的话，你可以给我一个最新复现的代码片段

**Comment by eamd-wq** [comment]
> **直接写defaultValue是正常的** ? 你的 defaultValue 是一个原始值吗？方便的话，你可以给我一个最小复现的代码片段吗？

https://github.com/eamd-wq/vue3-antdv-admin

拉取这个项目运行
复现操作：系统管理>数据字典>新增>确定
文件路径：src\views\system\dict-type\formSchemas.ts

**Comment by buqiyuan** [comment]
🤔 啊这不是跟线上代码一样吗？没复现

https://github.com/buqiyuan/vue3-antdv-admin/assets/39730999/e6458a51-ca2b-4176-9dfe-40abc152e8f4

**Comment by eamd-wq** [comment]
> https://github.com/eamd-wq/vue3-antdv-admin

刚刚网络有问题没有推送上去 你再看下

**Comment by buqiyuan** [comment]
OK，复现了，就是说 通过 `componentProps` 设置的 `defaultValue` 是有问题的，而直接声明在最外层的 `schema` 身上的 `defaultValue` 是正常的

**Comment by eamd-wq** [comment]
> OK，复现了，就是说 通过 `componentProps` 设置的 `defaultValue` 是有问题的，而直接声明在最外层的 `schema` 身上的 `defaultValue` 是正常的

对的，但是 schema 身上的 defaultValue 也并非没问题，我又提交了一个代码 你可以对比下三个备注的区别

**Comment by eamd-wq** [comment]
> > OK，复现了，就是说 通过 `componentProps` 设置的 `defaultValue` 是有问题的，而直接声明在最外层的 `schema` 身上的 `defaultValue` 是正常的
> 
> 对的，但是 schema 身上的 defaultValue 也并非没问题，我又提交了一个代码 你可以对比下三个备注的区别

import type { FormSchema } from '@/components/core/schema-form/';

const defaultValue = '备注信息1\n备注信息2\n备注信息3\n备注信息4\n备注信息5\n备注信息6';

export const baseSchemas: FormSchema<API.DictTypeDto>[] = [
  {
    field: 'name',
    component: 'Input',
    label: '字典名称',
    rules: [{ required: true, type: 'string' }],
    componentProps: {
      defaultValue: '默认值测试',
    },
  },
  {
    field: 'code',
    component: 'Input',
    label: '字典编码',
    rules: [{ required: true, type: 'string' }],
    componentProps: {
      defaultValue: 'test_default_value',
    },
  },
  {
    field: 'status',
    label: '状态',
    component: 'RadioGroup',
    defaultValue: 1,
    componentProps: {
      options: [
        { label: '启用', value: 1 },
        { label: '禁用', value: 0 },
      ],
    },
  },
  {
    field: 'remark',
    component: 'InputTextArea',
    label: '备注',
    colProps: {
      span: 24,
    },
    componentProps: {
      defaultValue,
    },
  },
  {
    field: 'remark',
    component: 'InputTextArea',
    label: '备注',
    colProps: {
      span: 24,
    },
    componentProps: {
      autoSize: true,
      defaultValue,
    },
  },
  {
    field: 'remark',
    component: 'InputTextArea',
    label: '备注',
    colProps: {
      span: 24,
    },
    defaultValue,
    componentProps: {
      autoSize: true,
    },
  },
];


代码退步上去 网络有点问题 这是这个文件我改动后的最终结果

**Comment by buqiyuan** [comment]
啊这，给你推荐一个便宜好用的梯子：https://tapfog.com/

**Comment by eamd-wq** [comment]
> 啊这，给你推荐一个便宜好用的梯子：https://tapfog.com/

哈哈

**Comment by eamd-wq** [comment]
> 啊这，给你推荐一个便宜好用的梯子：https://tapfog.com/

推上去了 梯子换了个节点

**Comment by buqiyuan** [comment]
关于 `autoSize` 这个 bug，以下代码可以复现：
```vue
<template>
  <a-textarea v-model:value="inputValue" placeholder="Basic usage" auto-size />
</template>

<script lang="ts" setup>
  import { ref, onMounted } from 'vue';
  const inputValue = ref();

  onMounted(() => {
    inputValue.value = '出 Bug 啦！';
  });
</script>
```
感兴趣你可以研究一下~

**Comment by eamd-wq** [comment]
> 关于 `autoSize` 这个 bug，以下代码可以复现：
> 
> ```
> <template>
>   <a-textarea v-model:value="inputValue" placeholder="Basic usage" auto-size />
> </template>
> 
> <script lang="ts" setup>
>   import { ref, onMounted } from 'vue';
>   const inputValue = ref();
> 
>   onMounted(() => {
>     inputValue.value = '出 Bug 啦！';
>   });
> </script>
> ```
> 
> 感兴趣你可以研究一下~

你的nest项目和这个项目代码为何如此优雅 有什么诀窍吗 我技术成长遇到瓶颈了 我感觉我的水平写不出这种代码
原理啥的都懂 可能就是做不到这种优雅得拆分和设计

**Comment by eamd-wq** [comment]
你有wx交流群吗 一起交流一下

**Comment by buqiyuan** [comment]
- 是当文本框值变化时 antdv 里面相关 watch 回调执行的顺序问题。
- 兄die过誉了！我只能说：多看、多写，唯手熟尔~
- 没有建群哦！有问题在 issue 反馈就好。

**Comment by eamd-wq** [comment]
> * 是当文本框值变化时 antdv 里面相关 watch 回调执行的顺序问题。
> * 兄die过誉了！我只能说：多看、多写，唯手熟尔~
> * 没有建群哦！有问题在 issue 反馈就好。
牛牪犇
