### ISSUE TITLE
BUG!!   columns的dataIndex属性

### ISSUE THREAD

**Issue by tiantianliulang** [buqiyuan/vue3-antdv-admin#173]
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/77230009/de1b7f6f-b51a-4b2e-b3c8-a18b27250008)

重新步骤: 
任务日志界面，search = true，dataIndex如果是数组格式，会报错
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/77230009/fa53fac7-0cdd-4051-bad3-1d56d1836576)

**Comment by buqiyuan** [comment]
已修复：https://github.com/buqiyuan/vue3-antdv-admin/commit/7416c5231bed61851ef4acb5c09d3453f7c4b9d4
