### ISSUE TITLE
请问大神 全局 API 是如何做到的

### ISSUE THREAD

**Issue by itwmike** [buqiyuan/vue3-antdv-admin#174]
![1712808327454](https://github.com/buqiyuan/vue3-antdv-admin/assets/6613191/ca39bcf4-7a9f-4656-84ee-bdd8fa1fd9e8)
这个是如何做到能够全局访问的，为啥我在我的项目里定义了一个访问不到。
![1712808437908](https://github.com/buqiyuan/vue3-antdv-admin/assets/6613191/03071acd-495b-4dbd-b716-7e68f240ad2c)

**Comment by buqiyuan** [comment]
https://github.com/buqiyuan/vue3-antdv-admin/blob/7416c5231bed61851ef4acb5c09d3453f7c4b9d4/tsconfig.json#L40-L50
🤔按理说，你定义的 `packages/api/typings.d.ts` 已经满足了  `"**/*.d.ts" ` 匹配规则，全局的命名空间应该生效了才对。实在不行，你可以将你的 `.d.ts` 文件路径写入到 `types` 中：
```json
{
  "compilerOptions": {
    "types": ["./packages/api/typings.d.ts"]
  }
}
```
