### ISSUE TITLE
表单设置layout: 'vertical'   样式会有问题

### ISSUE THREAD

**Issue by 732124645** [buqiyuan/vue3-antdv-admin#175]
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/783eab4e-816e-4f44-96d5-15e75fa02fcf)
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/4797cacf-03b2-4ab8-83d1-9f0f6074c120)

**Comment by buqiyuan** [comment]
把 `labelWidth` 属性注释掉应该就正常了

**Comment by 732124645** [comment]
辛苦大佬 请大佬喝杯咖啡
