### ISSUE TITLE
菜单冲突

### ISSUE THREAD

**Issue by datalymin** [buqiyuan/vue3-antdv-admin#178]
## Bug report（问题描述）
创建新菜单时，如果新菜单名称与原有菜单的名称相同，则两个菜单会发生冲突，尽管两个菜单不在同一级目录下。
#### Steps to reproduce（问题复现步骤）
1.创建新菜单，如菜单名称与原有的 **系统管理/用户管理** 菜单相同，但是路由地址和文件地址不同，新菜单位于根目录

![1](https://github.com/buqiyuan/vue3-antdv-admin/assets/166972295/2061b0e7-04d3-49a9-8e29-f690f8f9336a)

2.创建完成后，点击新菜单时，**系统管理/用户管理** 菜单也会显示被点击。且如果先点击 **系统管理/用户管理** 菜单则是会跳转到新菜单设置的路由地址。

![2](https://github.com/buqiyuan/vue3-antdv-admin/assets/166972295/f5726cb7-5aca-428f-a683-6364f9e867cf)

**Comment by buqiyuan** [comment]
通过拼接父路由 name 修复：
https://github.com/buqiyuan/vue3-antdv-admin/blob/f149b6f30f6911e550ca69f54d1c7d08ae56dde6/src/router/helper/routeHelper.tsx#L40-L43

**Comment by buqiyuan** [comment]
想了下，动态生成路由时，还是以路由的路径作为路由的唯一名称比较合适，改动如下：
https://github.com/buqiyuan/vue3-antdv-admin/commit/8e0aa45d83a7f2a5ec3dc6d5c23e7fb9c8d21d5f#diff-b3f0d655e949d28204a0f487016378e19515b879c460edbe782c1f1c4986e3a0
