### ISSUE TITLE
Eslint性能问题

### ISSUE THREAD

**Issue by eamd-wq** [buqiyuan/vue3-antdv-admin#186]
最新版
windows-11中使用vscode开发时会明显感觉到性能较差
写得快的时候语法提示和保存都有明显延迟

**Comment by renqian805** [comment]
试下开启以下的配置：
https://github.com/buqiyuan/vue3-antdv-admin/blob/63aa9c06b9b87d277a7f6115abc5e52dc90c55b1/.vscode/settings.json#L6-L9

**Comment by eamd-wq** [comment]
好呢 我试试

**Comment by eamd-wq** [comment]
还是挺卡的

**Comment by MrFriedRice** [comment]
![image](https://github.com/user-attachments/assets/f32ccdc9-bb66-488b-b371-4b90455d6231)
没用咋回事  没下插件吗 @renqian805
