### ISSUE TITLE
一个组件内多个表格，dynamicTableInstance 怎么用

### ISSUE THREAD

**Issue by itwmike** [buqiyuan/vue3-antdv-admin#191]
## Feature request（新功能建议）
一个组件内有2个table时 ，
const [DynamicTable, dynamicTableInstance] = useTable(); 

dynamicTableInstance 如何区分

**Comment by renqian805** [comment]
这个名字可以随便起的
const [DynamicTable1, dynamicTableInstance1] = useTable();
const [DynamicTable2, dynamicTableInstance2] = useTable();
