### ISSUE TITLE
table编辑行的时候，我保存的时候我只想把数据同步到表格中，只想并不想调用保存的接口，这个可以实现吗

### ISSUE THREAD

**Issue by 732124645** [buqiyuan/vue3-antdv-admin#193]

**Comment by buqiyuan** [comment]
🤔可以啊！将修改后的`行数据`合并到`原行数据`中就好了
https://github.com/buqiyuan/vue3-antdv-admin/blob/37be45112789470155b3c5a8095e7be49a4d314b/src/views/demos/tables/edit-row-table/index.vue#L102-L105

```diff
const handleSave: OnSave = async (rowKey, record, originRow) => { 
     console.log('handleSave', rowKey, record, originRow); 
     await waitTime(2000); 
++   Object.assign(originRow, record);
   }; 
```

**Comment by buqiyuan** [comment]
```js
Object.assign(record, { 
   ...result, 
   img: result.img[0]?.thumbUrl || record.img, 
 }); 
```
https://github.com/buqiyuan/vue3-antdv-admin/blob/11a29dd0bfcebedde2c4f98edf88f53fdacf22bf/src/views/demos/tables/edit-row-table/index.vue#L67-L82
