### ISSUE TITLE
当我在columns.tsx中使用i18n,切换语言的时候，内容并没有变

### ISSUE THREAD

**Issue by 732124645** [buqiyuan/vue3-antdv-admin#202]
代码见图片
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/ab645497-8f2f-4aa9-ba31-a4fe09e215f8)
效果
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/0b14492a-afc8-44e1-9acb-15c9fcafc7d3)
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/3ec64261-c781-46b5-88e0-9e70586031de)

**Comment by 732124645** [comment]
如果columns用函数的方式返回回去，表格是好的，但是查询条件会有问题
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/3439d230-771e-41ef-8620-d969c7d9324f)
效果
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/3beb5499-ac52-42a5-baf8-a13491835545)
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/52958359/98578385-8bcf-4dd9-a427-f24562e5e07c)

**Comment by buqiyuan** [comment]
动态内容需要写成函数的形式，例如：
```ts
{
  title: () => t('common.back')
}
```
