### ISSUE TITLE
现在带有多选功能的表格，在隐藏任意列的时候会多带出一列序号列。怀疑是fix #204 时候出的问题

### ISSUE THREAD

**Issue by SanaiSho** [buqiyuan/vue3-antdv-admin#206]
#### Steps to reproduce（问题复现步骤）

1. 以用户管理模块为例，打开模块
2. 在自定义的列字段里多出现了一个可勾选的序号列，且与顶部序号列控制可以单独生效。
3. 点击表格右上角的设置隐藏列功能，取消勾选除序号外的列，序号列会变为两列。

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/buqiyuan/vue3-antdv-admin/assets/171128158/eec21c2a-8238-4c9b-98f2-7c0cb50a232c)

**Comment by buqiyuan** [comment]
感谢指出！已修复
