### ISSUE TITLE
formSchemas如何引用自己封装的组件呢，插槽如何添加呢。

### ISSUE THREAD

**Issue by Fluox-Etine** [buqiyuan/vue3-antdv-admin#217]
formSchemas如何引用自己封装的组件呢，插槽如何添加呢。请教下？？？？

**Comment by buqiyuan** [comment]
参考：
https://github.com/buqiyuan/vue3-antdv-admin/blob/9eb521693c73f14bccaa075bda69f1ea004091b7/src/views/demos/form/custom-form/index.vue#L47-L94
