### ISSUE TITLE
edge更新后打不开网页（129.0.2792.52 (正式版本) (64 位)）

### ISSUE THREAD

**Issue by FerretAngel** [buqiyuan/vue3-antdv-admin#218]
## Bug report（问题描述）
当edge更新到129.0.2792.52 (正式版本) (64 位)后网页无法正常加载
#### Steps to reproduce（问题复现步骤）
将edge更新到129.0.2792.52 (正式版本) (64 位)后无法打开网页

#### Link to minimal reproduction（最小可在线还原 demo）
示例程序也是如此
[](https://github.com/buqiyuan/vue3-antdv-admin/)

#### Other relevant information（格外信息）

- Your OS:
- Node.js version:
- packageManager:

**Comment by q925148682** [comment]
Google Chrome 129.0.6668.59  9月18号版本更新后，打包完生产环境也打不开

**Comment by FerretAngel** [comment]
> Google Chrome 129.0.6668.59 9月18号版本更新后，打包完生产环境也打不开

老哥，对于这个问题你有什么头绪吗？

**Comment by q925148682** [comment]
> > Google Chrome 129.0.6668.59 9月18号版本更新后，打包完生产环境也打不开
> 
> 老哥，对于这个问题你有什么头绪吗？
楼下老哥厉害，我搞了好几天没有头绪

**Comment by haoqing** [comment]
我也出现了这个问题

**Comment by haoqing** [comment]
> 同样的问题，edge和Chrome最新版本，打包完生产环境打不开。 经过简单调试，代码卡在 await router.isReady(); ，后续代码就不会在执行了。 （PS：这段代码注释了就能正常打开了，但是还没测试会对项目有没有其它副影响） 源主求助！！！

没用

**Comment by FerretAngel** [comment]
> > 同样的问题，edge和Chrome最新版本，打包完生产环境打不开。 经过简单调试，代码卡在 await router.isReady(); ，后续代码就不会在执行了。 （PS：这段代码注释了就能正常打开了，但是还没测试会对项目有没有其它副影响） 源主求助！！！
> 
> 没用

我注释了之后就正常了

**Comment by yfengn** [comment]
同样的问题，edge 和 Chrome 新版本，生产环境打不开, 之前能正常使用，现在打开空白，请问有解决方案吗

**Comment by FerretAngel** [comment]
> 同样的问题，edge 和 Chrome 新版本，生产环境打不开, 之前能正常使用，现在打开空白，请问有解决方案吗

https://github.com/buqiyuan/vue3-antdv-admin/issues/218#issuecomment-2367315948

**Comment by Sunshine168** [comment]
locales/index.ts 里的 await createI18nOptions 也可能会导致这个问题， 修改一下即可

**Comment by achen240910** [comment]
有解决吗？我现在打包后edge和chrome浏览器都打不开了

**Comment by yfengn** [comment]
> 有解决吗？我现在打包后edge和chrome浏览器都打不开了

试试移除  await router.isReady();  并且确定把 .env 中的 VITE_MOCK_IN_PROD 改为 false

**Comment by achen240910** [comment]
@yfengn 多谢,解决了

**Comment by haoqing** [comment]
在main.ts把Mock注释掉就可以了
