### ISSUE TITLE
await没有在async函数中使用，导致出现错误。

### ISSUE THREAD

**Issue by shunshun66** [buqiyuan/vue3-antdv-admin#219]
在文件src/locales/index.ts中下面的这段代码有问题。编译以后在谷歌浏览器打不开网页。

const options = await createI18nOptions();
export const i18n = createI18n(options);

// setup i18n instance with global
export function setupI18n(app: App) {
  app.use(i18n);
}

原因是：const options = await createI18nOptions(); 这段代码应该在 async  函数中使用。

修改后的代码如下：
let i18n: any;

export async function setupI18n(app: App) {
  const options = await createI18nOptions();
  i18n = createI18n(options);
  app.use(i18n);
}

export { i18n };

**Comment by buqiyuan** [comment]
感谢指出！已修复: b275a71431cebf19c1369c549d70fb5a42d2fe59
