### ISSUE TITLE
谷歌浏览器更新到最新版无法打开

### ISSUE THREAD

**Issue by TryingA** [buqiyuan/vue3-antdv-admin#220]
edge更新版本后也一样，版本 129.0.6668.90（正式版本） （64 位），
项目地址：https://uat.admin.jieshuo.cn/#/
部分文件无法加载，我看仓库里也有人提出了一样的问题

**Comment by buqiyuan** [comment]
Duplicate #218 

做出以下改动即可：
https://github.com/buqiyuan/vue3-antdv-admin/blob/58617f947941b754569ee69a176446f3ad412769/src/locales/index.ts#L31-L41

线上就是最新代码打包的，没发现问题

**Comment by haoqing** [comment]
> Duplicate #218
> 
> 做出以下改动即可：
> 
> https://github.com/buqiyuan/vue3-antdv-admin/blob/58617f947941b754569ee69a176446f3ad412769/src/locales/index.ts#L31-L41
> 
> 线上就是最新代码打包的，没发现问题

我把mock注释掉就好了
