### ISSUE TITLE
怎么给 Select 动态赋值

### ISSUE THREAD

**Issue by tiantianliulang** [buqiyuan/vue3-antdv-admin#74]
![image](https://user-images.githubusercontent.com/77230009/148149116-fa6d5e66-b345-42a7-9f66-f3c9e8291111.png)
![image](https://user-images.githubusercontent.com/77230009/148149153-3f3f4a38-d2b2-4eac-ade9-11ce6faa7bc3.png)
![image](https://user-images.githubusercontent.com/77230009/148149241-b13a0e82-c79a-4ee7-948b-6087923b0bef.png)

我输出有值的，但是下拉框里没数据，我的写法有问题嘛，谢谢

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/148152185-10251fc8-ee55-47bd-a842-bd3f09ffaf6a.png)
暂时先使用request方法进行异步数据填充吧！

**Comment by buqiyuan** [comment]
正常更新表单的值，需要通过调用表单内部的updateSchema来进行更新，目前我遗漏了将DynamicTable的QueryForm实例方法对外暴露了

**Comment by buqiyuan** [comment]
已更新，使用示例：https://github.com/buqiyuan/vue3-antd-admin/blob/75c9f557b19b00bfd8516246b56e9eeec127dd24/src/views/demos/tables/wzry-table/index.vue#L68

**Comment by tiantianliulang** [comment]
> 
OK  谢谢

**Comment by stevenliu87** [comment]
tiantianliulang 你的问题解决了吗 我也有这样的问题
  onSearch : async (val: string) =>{
      const optionSel=[] as Array<any>  
     const list = await getListApporgcode({ apporgcode: val });
 
     list.list.map((item)=>(
      console.log(item),
      optionSel.push({ label: item.apporgname, value: item.apporgcode })
     ));
     options: optionSel;   
      
  },
下拉框里不显示

**Comment by tiantianliulang** [comment]
> tiantianliulang 你的问题解决了吗 我也有这样的问题 onSearch : async (val: string) =>{ const optionSel=[] as Array const list = await getListApporgcode({ apporgcode: val });
> 
> ```
>  list.list.map((item)=>(
>   console.log(item),
>   optionSel.push({ label: item.apporgname, value: item.apporgcode })
>  ));
>  options: optionSel;   
> ```
> 
> }, 下拉框里不显示

解决了啊   看上面  作者已经说的很详细了

**Comment by stevenliu87** [comment]
是在做 新增功能，表单提交时用的，在onSearch : async (val: string) =>{里写的，能显示吗
