### ISSUE TITLE
 做 新增功能，表单提交时用的，在onSearch ,怎么给 Select 动态赋值 

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antdv-admin#79]
componentProps: {
      showSearch: true,
      onSearch: async (val: string) => {
        const optionSel = [] as Array<any>;
        const list = await getListApporgcode({ apporgcode: val });

        list.list.map(
          (item) => (
            console.log(item), optionSel.push({ label: item.apporgname, value: item.apporgcode })
          ),
        );
        options: optionSel;
      },
    },
  },
这样没有数据

**Comment by buqiyuan** [comment]
componentProps: ({ schemaFormRef, formModel }) => ({

**Comment by buqiyuan** [comment]
可以参考这里的写法，使用componentProps回调参数更新表单配置

https://github.com/buqiyuan/vue3-antd-admin/blob/0d2ad2f0dda2bc8ef064b3ecb7905ea809f5d2ad/src/views/demos/tables/search-table/columns.tsx#L63

**Comment by stevenliu87** [comment]
用的是export const roleSchemas: FormItemSchema<API.CreateDistributeConfirmParams>[] = [，不能用TableColumn吧

**Comment by stevenliu87** [comment]
好了 谢谢你
