### ISSUE TITLE
后续是否有路由菜单切割功能？

### ISSUE THREAD

**Issue by Elssia** [buqiyuan/vue3-antdv-admin#94]
首先感谢作者的辛苦付出。
现在布局所有的路由导航都在侧边栏或者顶部。能不能支持路由切割。一级导航在顶部。其他的在侧边栏

**Comment by buqiyuan** [comment]
后续会的，目前短期内没时间加新功能

**Comment by sunfeng90** [comment]
谢谢大佬的代码。你们是免费开源的吧？可以商用吧？

**Comment by sunfeng90** [comment]
发现后端项目打包后，就运行不了了。npm run build后的dist包，就无法运行了。
我现在用nohup, 直接在进程里面运行npm run start,，然后远程访问的。

**Comment by buqiyuan** [comment]
> 发现后端项目打包后，就运行不了了。npm run build后的dist包，就无法运行了。 我现在用nohup, 直接在进程里面运行npm run start,，然后远程访问的。

有关后端的项目，请在 [nest-admin](https://github.com/buqiyuan/nest-admin) 中反馈。
仅有`dist`的代码并不能直接执行，需要依赖于`node_modules`和`.env*`

**Comment by sunfeng90** [comment]
> > 发现后端项目打包后，就运行不了了。npm run build后的dist包，就无法运行了。 我现在用nohup, 直接在进程里面运行npm run start,，然后远程访问的。
> 
> 有关后端的项目，请在 [nest-admin](https://github.com/buqiyuan/nest-admin) 中反馈。 仅有`dist`的代码并不能直接执行，需要依赖于`node_modules`和`.env*`

nest-admin和这个项目有啥区别呢？

**Comment by sunfeng90** [comment]
> > > 发现后端项目打包后，就运行不了了。npm run build后的dist包，就无法运行了。 我现在用nohup, 直接在进程里面运行npm run start,，然后远程访问的。
> > 
> > 
> > 有关后端的项目，请在 [nest-admin](https://github.com/buqiyuan/nest-admin) 中反馈。 仅有`dist`的代码并不能直接执行，需要依赖于`node_modules`和`.env*`
> 
> nest-admin和这个项目有啥区别呢？

我想在登录旁边添加一个注册的按钮，然后不用token，如何使用admin/sys/user/add接口注册用户呢？

**Comment by sunfeng90** [comment]
目前接口都没有请求，页面就刷新了。还没有登录进系统，在系统外面注册新增用户。

**Comment by buqiyuan** [comment]
> > > 发现后端项目打包后，就运行不了了。npm run build后的dist包，就无法运行了。 我现在用nohup, 直接在进程里面运行npm run start,，然后远程访问的。
> > 
> > 
> > 有关后端的项目，请在 [nest-admin](https://github.com/buqiyuan/nest-admin) 中反馈。 仅有`dist`的代码并不能直接执行，需要依赖于`node_modules`和`.env*`
> 
> nest-admin和这个项目有啥区别呢？

额，我有点不明所以了。
- 首先你的 node 项目如果没有借助 webpack 等构建工具打包的话，仅凭单独的 dist 文件是无法运行的，因为没有将第三方模块一起打包进 dist。所以要么你使用 webpack 进行打包，要么在 dist 同级目录下执行 `yarn install --production` 安装生产依赖。
> PS：有报错请附上报错信息，仅一句无法运行，Who know what happen?
- 其次，非本仓库 bug 的业务问题，请自行解决
