### ISSUE TITLE
退出登录报错！

### ISSUE THREAD

**Issue by tiantianliulang** [buqiyuan/vue3-antdv-admin#98]
![image](https://user-images.githubusercontent.com/77230009/165233748-59ff30aa-4078-4e7a-bc81-f305c1fc9cad.png)

**Comment by tiantianliulang** [comment]
![screencast-vue3-antd-admin vercel app-2022 04 29-15_35_52](https://user-images.githubusercontent.com/77230009/165903630-86d6a33a-3eb3-4993-937a-ea88b632df37.gif)
就是在你的线上demo地址操作的， 具体看gif图， 这2个页面 我看菜单里都设置了 是否缓存 为 true，false的时候好像没这个问题

**Comment by buqiyuan** [comment]
不知道算不算是`keep-alive`和`transition`两个内置组件的问题，它们内部一些钩子执行的时机不太对，也没有做一些容错处理

**Comment by xliamh** [comment]
稳定安全，免费vpn, 支持chatgpt(https://monkeyff02.online/#/portal?c=ad01)
